-- 서비스 옵션 유형 카테고리 값 마이그레이션
-- 기존 ROOM_AMENITY → AMENITY 변환 (무료/유료 모두)

-- 무료 서비스 옵션 테이블
UPDATE rm_free_service_option SET service_type = 'AMENITY' WHERE service_type = 'ROOM_AMENITY';

-- 유료 서비스 옵션 테이블
UPDATE rm_paid_service_option SET service_type = 'AMENITY_PREMIUM' WHERE service_type = 'ROOM_AMENITY';

-- 컬럼 코멘트 갱신
COMMENT ON COLUMN rm_free_service_option.service_type IS '서비스 유형 (BED/VIEW/FLOOR/AMENITY/BREAKFAST/TRANSFER/PARKING/INTERNET/WELCOME/EARLY_CHECKIN/LATE_CHECKOUT/LOUNGE/POOL_FITNESS/KIDS/PET/SPECIAL_REQUEST)';
COMMENT ON COLUMN rm_paid_service_option.service_type IS '서비스 유형 (ROOM_UPGRADE/BED_EXTRA/BREAKFAST_PAID/MEAL/MINIBAR/ROOM_SERVICE/AMENITY_PREMIUM/SPA_WELLNESS/LAUNDRY/TRANSFER_PAID/PARKING_PAID/TOUR_ACTIVITY/CHILDCARE/BUSINESS/DECORATION/PHOTO/INTERNET_PAID/SAFE_LOCKER/MINI_KITCHEN/GIFT_PACKAGE)';
