-- 워크스테이션 테이블 (VAN 카드 단말기 연결 정보)
CREATE TABLE htl_workstation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL,
    ws_no VARCHAR(20) NOT NULL,
    ws_name VARCHAR(100),
    kpsp_host VARCHAR(255) NOT NULL DEFAULT 'localhost',
    kpsp_port INTEGER NOT NULL DEFAULT 19090,
    terminal_id VARCHAR(50),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    sort_order INTEGER DEFAULT 0,
    use_yn BOOLEAN NOT NULL DEFAULT TRUE,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    UNIQUE(property_id, ws_no)
);

-- VAN 시퀀스 번호 생성용 시퀀스
CREATE SEQUENCE van_sequence_no_seq START WITH 1 INCREMENT BY 1;

-- 모든 프로퍼티에 기본 워크스테이션 시드 데이터
INSERT INTO htl_workstation (property_id, ws_no, ws_name, kpsp_host, kpsp_port, terminal_id, created_by)
SELECT p.id, 'ADMIN', '프론트데스크', 'localhost', 19090, '0788888', 'system'
FROM htl_property p
WHERE p.deleted_at IS NULL;
